stages:
  - test

run_ui_tests:
  stage: test
  script:
    - echo "Chạy Login tests với TestNG"
    - cmd /c "mvn clean test -Dsurefire.suiteXmlFiles=testNG/test_login_web.xml"
  tags:
    - shell  # hoặc 'Windows'
  artifacts:
    when: always
    paths:
      - test-output/
      - target/surefire-reports/
    expire_in: 1 week
