stages:
  - build
  - test

build_project:
  stage: build
  script:
    - echo "Đang build project với Maven"
    - mvn clean install -DskipTests  # Chỉ build, không chạy test
  tags:
    - shell  # hoặc 'Windows'
  artifacts:
    paths:
      - target/
    expire_in: 1 day

run_ui_tests:
  stage: test
  script:
    - echo "Chạy Login tests Web với TestNG"
    - cmd /c "mvn clean test -Dsurefire.suiteXmlFiles=testNG/test_login_web.xml"
  tags:
    - shell  # hoặc 'Windows'
  dependencies:
    - build_project
  artifacts:
    when: always
    paths:
      - test-output/
      - target/surefire-reports/
    expire_in: 1 week