stages:
  - test

run_ui_tests:
  stage: test
  script:
    - echo "Chạy UI tests với TestNG"
    - mvn clean test -DsuiteXmlFile=testng.xml
  tags:
    - shell  # hoặc 'Windows' tùy runner bạn tag
  artifacts:
    when: always
    paths:
      - test-output/
      - target/surefire-reports/
    expire_in: 1 week
  reports:
    junit: target/surefire-reports/TEST-*.xml  # Cho phép GitLab hiển thị kết quả test
