stages:
  - test

check_runner:
  stage: test
  script:
    - echo "GitLab Runner đang hoạt động"
    - java -version
    - mvn -version
  tags:
    - shell  # Hoặc dùng "Windows" tùy runner bạn tag gì
