stages:
  - test

run_ui_tests:
  stage: test
  script:
    - echo "Chạy Login tests Web với TestNG"
    - cmd /c "mvn clean test -Dsurefire.suiteXmlFiles=testNG/test_login_web.xml"
#    - echo "Chạy Login tests App với TestNG"
#    - cmd /c "mvn clean test -Dsurefire.suiteXmlFiles=testNG/test_login_app.xml"
#    - echo %ANDROID_HOME%
#    - where adb
#    - where node
  tags:
    - shell  # hoặc 'Windows'
  artifacts:
    when: always
    paths:
      - test-output/
      - target/surefire-reports/
    expire_in: 1 week
