stages:
  - test

run_ui_tests:
  stage: test
  script:
    - echo "Chạy UI tests với TestNG"
    - mvn -DsuiteXmlFile=testng.xml clean test
  tags:
    - shell  # hoặc 'Windows'
  artifacts:
    when: always
    paths:
      - test-output/
      - target/surefire-reports/
    expire_in: 1 week
